AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create EC2 Instances

Resources:
  PublicEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: testkey
      SubnetId: !ImportValue PublicSubnetId
      SecurityGroupIds:
        - !ImportValue PublicSecurityGroupId
      ImageId: ami-0ebfd941bbafe70c6  # Replace with the correct AMI ID

  PrivateEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: testkey
      SubnetId: !ImportValue PrivateSubnetId
      SecurityGroupIds:
        - !ImportValue PrivateSecurityGroupId
      ImageId: ami-0ebfd941bbafe70c6  # Replace with the correct AMI ID

Outputs:
  PublicEC2InstanceId:
    Description: Public EC2 Instance ID
    Value: !Ref PublicEC2Instance

  PrivateEC2InstanceId:
    Description: Private EC2 Instance ID
    Value: !Ref PrivateEC2Instance
