name: Test AWS Infrastructure

on:
  push:
    branches:
      - test
    paths:
      - 'Terraform/**'
  pull_request:

jobs:
  vpc_test:
    name: Test VPC
    uses: ./.github/workflows/test_vpc.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  ec2_test:
    name: Test EC2 Instances
    uses: ./.github/workflows/test_ec2.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  nat_gateway_test:
    name: Test NAT Gateway
    uses: ./.github/workflows/test_nat_gateway.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  security_group_test:
    name: Test Security Groups
    uses: ./.github/workflows/test_security_groups.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  # terraform_apply:
  #   name: Apply Terraform Configuration
  #   runs-on: ubuntu-latest
  #   needs: [vpc_test, ec2_test, nat_gateway_test, security_group_test]
  #   - name: Checkout code
  #       uses: actions/checkout@v2

  #   - name: Set up Terraform
  #     uses: hashicorp/setup-terraform@v2
  #     with:
  #       terraform_version: 1.4.6

  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v1
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1
  #       aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

  #   - name: Apply Terraform
  #     working-directory: ./Terraform
  #     run: terraform apply
