name: Test AWS Infrastructure

on:
  push:
    branches:
      - test
    paths:
      - 'Terraform/**'
  pull_request:

jobs:
  vpc_test:
    name: Test VPC
    uses: ./.github/workflows/test_vpc.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  ec2_test:
    name: Test EC2 Instances
    uses: ./.github/workflows/test_ec2.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  nat_gateway_test:
    name: Test NAT Gateway
    uses: ./.github/workflows/test_nat_gateway.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}

  security_group_test:
    name: Test Security Groups
    uses: ./.github/workflows/test_security_groups.yaml
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}