name: Test VPC

on:
  workflow_call:
    inputs:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  test_vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Install AWS CLI
        run: |
          sudo apt-get install unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"




      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Test if VPC is created
        run: |
          VPC_ID=$(terraform output -raw vpc_id)
          if [ -z "$VPC_ID" ]; then
            echo "VPC not created!"
            exit 1
          else
            echo "VPC created successfully with ID: $VPC_ID"
          fi
