name: Test NAT Gateway

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true

jobs:
  test_nat_gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Initialize Terraform
        working-directory: ./Terraform
        run: terraform init

      - name: Plan Terraform
        working-directory: ./Terraform
        run: terraform plan

      - name: Test NAT Gateway
        run: |
          NAT_GW_ID=$(terraform output -raw nat_gateway_id)
          if [ -z "$NAT_GW_ID" ]; then
            echo "NAT Gateway not created!"
            exit 1
          else
            echo "NAT Gateway created with ID: $NAT_GW_ID"
          fi
